### PR TITLE
[BUGS]: Replies Endpoints Bug Fixes

### LINKED ISSUE #383: [BUG]: Replies Endpoint Bugs
### Describe the bug

- [x] PATCH /comments/:commentId/replies/:replyId/votes/upvote continously increasing vote with ownerId
- [x] PATCH /comments/:commentId/replies/:replyId/flag - same behaviour with comment flagging
- [x] GET /comments/:commentId/replies/:replyId/votes - returning array instead of totalvotes, upvote and downvote
- [x] POST /comments/:commentId/replies - returning votes, upvotes, downvotes and flags as arrays instead of numbers

### PR DESCRIPTION
**Pull request by oscar-ekeyekwu**
**Before submitting your PR for review**

- Run `npm run lint` to find errors in code syntax/format
- Run `npm run lint:fix` to fix all auto-fixable errors in source code and auto-format with prettier
- Ensure you fix any linting errors displayed after running any of the above commands

**What does this PR do?**

Fixes #383 
Fixed Replies endpoints bugs

**Description of Task to be completed?**

- [x] PATCH /comments/:commentId/replies/:replyId/votes/upvote continously increasing vote with ownerId
- [x] PATCH /comments/:commentId/replies/:replyId/flag - same behaviour with comment flagging
- [x] GET /comments/:commentId/replies/:replyId/votes - returning array instead of totalvotes, upvote and downvote
- [x] POST /comments/:commentId/replies - returning votes, upvotes, downvotes and flags as arrays instead of numbers

**How should this be manually tested?**

- Send a `PATCH` request to [ comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies/5f05aa5acad90e0017bdfffc/votes/upvote ](comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies/5f05aa5acad90e0017bdfffc/votes/upvote) with `{"ownerId": "user4@test.com"}`

-  Send a `PATCH` request to [ comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies/5f05aa5acad90e0017bdfffc/votes/flag ](comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies/5f05aa5acad90e0017bdfffc/flag) with `{"ownerId": "user4@test.com"}`

- Send a `GET` request to [comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies/5f05aa5acad90e0017bdfffc/votes](comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies/5f05aa5acad90e0017bdfffc/votes)

- Send a `POST` request to [comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies](comments-microservice.herokuapp.com/v1/comments/5f05a5e7cad90e0017bdfff9/replies) with `{
  "ownerId": "user2@replies.com",
  "content": "This is another reply to a comment"
}`

**Any background context you want to provide?**

Any pertinent information that should be considered

**What is the link to the issue on Github?**

[Issue #383 ](https://github.com/microapidev/comment-microapi/issues/383)

**Questions:**

If something is unclear or you want some questions to be addressed by your peers, mention them here

### CODE REVIEW

File: models/admins.js [hunk 1]
```diff
@@ -11,6 +11,7 @@ const AdminSchema = new Schema(
       type: String,
       lowercase: true,
       required: true,
+      unique: true,
```
Comment (dave-ok) [inline models/admins.js:14]: This is not needed. We already have a unique index on the email and organization Id. Within the same organization the same email cannot be registered twice. But the same email can be registered in a different organization. Otherwise you prevent users from registering in different organizations

Comment (oscar-ekeyekwu) [reply models/admins.js:14]: I was able to create two admins with one email

Comment (oscar-ekeyekwu) [reply models/admins.js:14]: I was able to create two admins with one email...unless that had already been resolved. I had made that commit since yesterday
